version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: openscore
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: openscore
      POSTGRES_USER: openscore
      POSTGRES_PASSWORD: openscore
    volumes:
      - database:/var/lib/postgresql/data
